source 'https://rubygems.org'

gem 'rails-api'
gem 'pg'
gem 'pg_search'
# Use Puma as the app server
gem 'puma'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# Action Cable dependencies for the Redis adapter
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'active_model_serializers'
gem 'kaminari'
gem 'api-pagination'
gem 'knock'
gem 'paranoia', github: 'rubysherpas/paranoia', branch: 'core'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner'
end

group :development do
  gem 'annotate'
end

group :test do
  gem 'rspec-rails', '3.5.0.beta1'
  gem 'rspec-mocks'
  gem 'shoulda-matchers', '~> 3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
